name: Simple CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Step 1: Checkout your repository
    - run: echo "Hello, DevOps!"  # Step 2: Print a simple message to verify the pipeline runs
