name: CI Pipeline with Shell Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Check out the code
    - name: Run Shell Script
      run: bash script.sh  # Execute the script.sh file
