name: Run Shell Script

on:
  push:
    branches:
      - main # This will run the workflow when code is pushed to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run hello_world.sh
        run: ./hello_world.sh
